DROP TABLE IF EXISTS User CASCADE;
DROP TABLE IF EXISTS Vote CASCADE;
DROP TABLE IF EXISTS Report CASCADE;
DROP TABLE IF EXISTS ReportType CASCADE;
DROP TABLE IF EXISTS Comment CASCADE;

CREATE TABLE User (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email VARCHAR(255) NOT NULL,
  user_password VARCHAR(255) NOT NULL,
  country VARCHAR(255) NOT NULL,
  province_or_state VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  street VARCHAR(255) NOT NULL
);

CREATE TABLE Report (
  id SERIAL PRIMARY KEY NOT NULL,
  report_description TEXT NOT NULL,
  character_amount INTEGER NOT NULL,
  gps_coordinates VARCHAR(255) NOT NULL
);

CREATE TABLE Vote (
  id SERIAL PRIMARY KEY NOT NULL,
  up_vote INTEGER NOT NULL,
  down_vote INTEGER NOT NULL,
  user_id INTEGER REFERENCES User(id) ON DELETE CASCADE,
  report_id INTEGER REFERENCES Report(id) ON DELETE CASCADE
);

CREATE TABLE ReportType (
  id SERIAL PRIMARY KEY NOT NULL,
  code_red BOOLEAN NOT NULL,
  email VARCHAR(255) NOT NULL,
  report_id INTEGER REFERENCES Report(id) ON DELETE CASCADE
);

CREATE TABLE Comment (
  id SERIAL PRIMARY KEY NOT NULL,
  comment VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES User(id)  ON DELETE CASCADE,
  report_id INTEGER REFERENCES Report(id) ON DELETE CASCADE
);